//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfKaktus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kaktus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kaktus()
        {
            this.Collection = new HashSet<Collection>();
        }
    
        public int id_kaktus { get; set; }
        public Nullable<int> id_kaktusType { get; set; }
        public string From { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<double> Price { get; set; }
        public string Uhod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Collection> Collection { get; set; }
        public virtual KaktusType KaktusType { get; set; }
    }
}
